col_names <- names(admissions)
admissions[,col_names] <- lapply(admissions[,col_names] , factor)
library(arules)
rules.all <- apriori(admissions)
rules <- apriori(admissions, control = list(verbose=F), parameter = list(minlen=2, supp=0.005, conf=0.8))
source("http://bioconductor.org/biocLite.R")
biocLite("Rgraphviz")
rules.sorted <- sort(rules, by="confidence")
inspect(rules.sorted)
library(arulesViz)
plot(rules.sorted)
